# Generated by Django 4.0.3 on 2025-06-07 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('work_required', models.TextField()),
                ('reported_by', models.CharField(max_length=100)),
                ('department_of_reporter', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('carpentry', 'Carpentry'), ('building', 'Building'), ('painting', 'Painting')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('awaiting_spares', 'Awaiting Spares'), ('done', 'Done')], default='pending', max_length=20)),
                ('time_submitted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
