# Generated by Django 4.0.3 on 2025-06-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
